# Base image for build
FROM node:18 as build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Nginx to serve the build
FROM nginx:alpine

# Copy build files
COPY --from=build /app/build /usr/share/nginx/html

# Remove default Nginx config and use custom one
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

