# Base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy files
COPY package*.json ./
RUN npm install

COPY . .

# Expose backend port
EXPOSE 5000

# Start the server
CMD ["npm", "start"]

