---
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Install PHP and required modules
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
      - php-cli
      - php-xml
      - php-curl
      - php-gd
      - php-xmlrpc
    state: present
    update_cache: yes

- name: Download and Extract WordPress
  become: yes
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz


- name: Extract WordPress Archive
  become: yes
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes


- name: Set Permissions
  become: yes
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Create wp-config.php
  become: yes
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

