---
- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create WordPress Database
  mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: "1"

