apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails-app
          image: thakurbharat75/rails-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@db:5432/postgres"
