name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    - name: Copy index.html to EC2
      run: |
        # Clone the repo on the EC2 instance
        ssh -o StrictHostKeyChecking=no ubuntu@3.84.14.67 << 'EOF'
          # Navigate to home directory or any desired location
          cd ~
          # Clone the repository
          git clone https://github.com/thakurbharat75/BTcloud.git

          # Navigate to the repository directory
          cd Btcloud

          # Checkout the main branch (or the branch you want)
          git checkout main

          # Copy index.html to /var/www/html
          sudo cp index.html /var/www/html/index.html

          # Restart Apache
          sudo systemctl restart apache2
        EOF


    - name: Restart Apache
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.84.14.67  'sudo systemctl restart apache2'
        ssh -o StrictHostKeyChecking=no ubuntu@44.212.22.146  'sudo systemctl restart apache2'
